In [1]:
import numpy as np 

print("Numpy version:", np.__version__)

Numpy version: 2.3.4


In [ ]:
arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])

arr3 = np.array([[[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]]])


print(type(arr1))
print(type(arr2))
print(type(arr3))

print("Dimension:",arr1.ndim)
print("Dimension:",arr2.ndim)
print("Dimension:",arr3.ndim)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Dimension: 1
Dimension: 2
Dimension: 3


In [ ]:
my_list = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],
                    [[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]],
                    [[25, 26, 27, 28],[29, 30, 31, 32],[33, 34, 35, 36]]])

print(my_list)

print(my_list.ndim)
print()

# [row:column:value]

# chain indexing

print("value:",my_list[2,1,3])
print()

print("value:",my_list[1][0][2])

print(my_list.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
3

value: 32

value: 15
(3, 3, 4)


In [ ]:
# concatenation

my_list = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],
                    [[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]],
                    [[25, 26, 27, 28],[29, 30, 31, 32],[33, 34, 35, 36]]])

word = my_list[2,2,2] + my_list[2,2,2] + my_list[0,1,0]

print("value :",word)

value : 75
