Creating Array

In [20]:
import numpy as np

In [21]:
print(np.zeros((2,2),dtype='int64'))          # 2x2 matrix storing only integers

[[0 0]
 [0 0]]


In [22]:
print(np.ones((3,3)))                         # 3x3 matrix with all values as 1

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
print(np.zeros((3,3)))                        # 3x3 matrix with all values as 1  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.zeros_like(np.ones((3,3))))          # 3x3 matrix with all values as 0 using zeros_like function     

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.full((3,3),10))                      # fill the given number using full function     

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [31]:
print(np.full_like(np.zeros((3,3)),10))       # fill the given number using full function with the help of zeros_like function

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [ ]:
print(np.eye(3))                              # identity matrix 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.identity(5))                       # identity matrix with the help of identity function

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
print(np.arange(1,100))                       # aranging numbers        

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [36]:
print(np.linspace(0,1,5))                     # 5 numbers between 0 and 1

[0.   0.25 0.5  0.75 1.  ]


In [37]:
print(np.empty((5,5)))                        # creates a empty spaces or any values in the matrix

[[1.08238830e-311 1.08238824e-311 1.69121096e-306 2.22521103e-306
  1.33509796e-306]
 [1.11261434e-306 2.22523004e-307 1.78020440e-306 1.33510679e-306
  2.22522597e-306]
 [1.33511290e-306 1.11258854e-306 1.11261502e-306 1.42410839e-306
  7.56597770e-307]
 [6.23059726e-307 1.42419530e-306 1.11261027e-306 1.69118515e-306
  9.34607074e-307]
 [1.69118787e-306 1.29061414e-306 1.42410974e-306 2.56761491e-312
  2.56761491e-312]]


In [ ]:
arr = np.array([[1 ,2 ,3]])                   # creating a numpy array
repeat = np.repeat(arr,2 , axis = 0)          # repeat the given number for 2 times
print(repeat)

[[1 1 2 2 3 3]]


creating a array like this

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
output : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
