Creating Array

In [1]:
import numpy as np

In [ ]:
print(np.zeros((2,2),dtype=int))    # 2x2 matrix storing only integers
print()
print(np.ones((3,3)))               # 3x3 matrix with all values as 1
print()          
print(np.full((3,3),10))            # fill the given number using full function
print()          
print(np.eye(3))                    # identity matrix 
print()          
print(np.arange(1,100))             # aranging numbers
print()          
print(np.linspace(0,1,5))           # 5 numbers between 0 and 1
print()
print(np.empty((5,5)))              # creates a empty spaces or any values in the matrix

[[0 0]
 [0 0]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]

[0.   0.25 0.5  0.75 1.  ]

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.22521103e-306
  1.33509796e-306]
 [1.11261434e-306 2.22523004e-307 1.78020440e-306 1.33510679e-306
  2.22522597e-306]
 [1.33511290e-306 1.11258854e-306 1.11261502e-306 1.42410839e-306
  7.56597770e-307]
 [6.23059726e-307 1.42419530e-306 1.11261027e-306 1.69118515e-306
  9.34607074e-307]
 [1.69118787e-306 1.29061414e-306 1.42410974e-306 2.56761491e-312
  2.56761491e-312]]


Array attributes

In [ ]:
arr = np.array([[1 ,2 ,3],[4 ,5 ,6]])

print("shape of array\t:",arr.shape)  # shape of array

print("dimension\t: ",arr.ndim)   # dimension

print("Total elements\t: ",arr.size)   # Total elements

print("data type\t: ",arr.dtype)  # data type

shape of array	: (2, 3)
dimension	:  2
Total elements	:  6
data type	:  int64


mathematical functions

In [44]:
arr1 = np.array([1 ,2 ,3])
arr2 = np.array([4 ,5 ,6])


print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Statistical functions

In [45]:
arr = np.array([1 , 2 ,3 ,4 ,5])

print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.sum())

3.0
5
1
15
