In [ ]:
# scalar arithmetic

import numpy as np

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
arr = np.array([1 ,2 ,3])

print(arr + 1)
print(arr - 2)
print(arr * 3)
print(arr / 4)
print(arr ** 5)

In [ ]:
# Vectorised math functions

arr = np.array([1.01 ,2.5 ,3.99])

print(np.sqrt(arr))
print()

print(np.round(arr))
print()

print(np.ceil(arr))
print()

print(np.floor(arr))
print()

print("pi value: ",np.pi)
print()

[1.00498756 1.58113883 1.99749844]

[1. 2. 4.]

[2. 3. 4.]

[1. 2. 3.]

pi value:  3.141592653589793



In [ ]:
# arthmetic operators

arr1 = np.array([1 ,2 ,3])
arr2 = np.array([4 ,5 ,6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)
print(arr1 // arr2)
print(arr1 % arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[0 0 0]
[1 2 3]


In [28]:
import numpy as np

# comparison operators

scores = np.array([91 ,55 ,100 ,73 ,82 ,64])

print(scores == 100)
print(scores >= 60)
print(scores <  60)


scores[scores < 60] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]
