FILTERING

In [1]:
import numpy as np

ages = np.array([[21 ,22 , 23, 24, 16, 17, 18]
                 ,[34 ,22 ,33 ,28 ,44, 57, 77]])

teenagers = ages[ages < 18]

adults = ages[(ages < 18) | (ages < 65)]

seniors = ages[(ages>= 65)]

evens = ages[ages % 2 == 0]

odds = ages[ages % 2 != 0]

print(seniors)
print(teenagers)
print(adults)
print(evens)
print(odds)

[77]
[16 17]
[21 22 23 24 16 17 18 34 22 33 28 44 57]
[22 24 16 18 34 22 28 44]
[21 23 17 33 57 77]


In [15]:
import numpy as np

ages = np.array([[21 ,22 , 23, 24, 16, 17, 18]
                 ,[34 ,22 ,33 ,28 ,44, 57, 77]])

adults = np.where(ages >= 18,ages,0)
adults1 = np.where(ages >=65 ,ages,1)

print(adults)
print(adults1)

[[21 22 23 24  0  0 18]
 [34 22 33 28 44 57 77]]
[[ 1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1 77]]
