In [ ]:
import numpy as np

my_list = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

# my_list[start:end:step]
# [row:column:]

print(my_list[0:4])
print()

print(my_list[1:3])
print()

print(my_list[0:4:2])
print()

print(my_list[0:4:1])
print()

print(my_list[::-2])
print()



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[13 14 15 16]
 [ 5  6  7  8]]

[ 2  6 10 14]


In [ ]:
import numpy as np

my_list = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])


print(my_list[:,0])
print(my_list[:,1])
print(my_list[:,2])
print(my_list[:,3])
print(my_list[:,-1])
print(my_list[:,-2])
print(my_list[::-1])

print()


[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[ 4  8 12 16]
[ 3  7 11 15]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

[ 2  6 10 14]

[ 2  6 10 14]



In [ ]:
import numpy as np

my_list = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

print(my_list[:,0:3])
print()
print(my_list[:,1:4])
print()
print(my_list[:,0:4:2])
print()
print(my_list[:,1])
print()
print(my_list[:,-3])
print()

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

[ 2  6 10 14]

[ 2  6 10 14]



In [64]:
import numpy as np

my_list = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])


print(my_list[0:2,0:2])
print()
print(my_list[0:2,2:4])
print()
print(my_list[1:3,1:3])
print()
print(my_list[2:4,2:4])
print()
print(my_list[1:3,2:4])
print()
print(my_list[2:4,1:3])
print()
print(my_list[2:,1:3])
print()


[[1 2]
 [5 6]]

[[3 4]
 [7 8]]

[[ 6  7]
 [10 11]]

[[11 12]
 [15 16]]

[[ 7  8]
 [11 12]]

[[10 11]
 [14 15]]

[[10 11]
 [14 15]]

