RESHAPE - used to change the shape of an array (eg. 1D to 2D)

In [3]:
import numpy as np

arr = np.array([1 ,2 ,3 ,4 ,5 ,6])

print("original array: ",arr)

print()

print(np.reshape(arr,(2,3)))
reshaped = np.reshape(arr , (2,3))
print(reshaped)

print()
reshaped[0][0] = 100
print(reshaped)

original array:  [1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

[[100   2   3]
 [  4   5   6]]


RAVEL - flattens the multi-dimensinal array into a 1d array

In [4]:

arr = np.array([[1 ,2 ,3],[4 ,5 ,6]])
arr1 = np.array([[[1 ,2 ,3],[4 ,5 ,6],[7 ,8 ,9 ]]])

print(arr.ndim)
print(arr1.ndim)

print("original array: ",arr)

ravel = arr.ravel()
print("ravel :",ravel)

ravel1 = arr1.ravel()

print("ravel :",ravel1)

ravel[0] = 100
print(arr)

2
3
original array:  [[1 2 3]
 [4 5 6]]
ravel : [1 2 3 4 5 6]
ravel : [1 2 3 4 5 6 7 8 9]
[[100   2   3]
 [  4   5   6]]


FLATTEN - similar to ravel() , but returns a copy (changes do not affect the original array)

In [14]:
arr = np.array([[1 ,2 ,3],[4 ,5 ,6]])

flatten = arr.flatten()
print(flatten)

flatten[0] = 100
print("flatten: ",flatten) 
print("Original array: ",arr)

[1 2 3 4 5 6]
flatten:  [100   2   3   4   5   6]
Original array:  [[1 2 3]
 [4 5 6]]


hstack - join arrays horizontally (along axis 1)

vstack - join arrays vertically (along axis 0)

In [18]:
arr1 = np.array([1 ,2 ,3 ,4])
arr2 = np.array([5 ,6 ,7 ,8])

print("original array: " , arr1,arr2)

print("hstack: ",np.hstack([arr1, arr2]))

print("vstack: ",np.vstack([arr1, arr2]))

original array:  [1 2 3 4] [5 6 7 8]
hstack:  [1 2 3 4 5 6 7 8]
vstack:  [[1 2 3 4]
 [5 6 7 8]]


concatenate - Can concatenate along any axis

In [28]:
arr1 = np.array([1 ,2 ,3 ,4])
arr2 = np.array([5 ,6 ,7 ,8])

print("concatenate: ",np.concatenate([arr1, arr2]))

arr3 = np.array([[[1 ,2] ,[3 ,4],[5 ,6]]])
arr4 = np.array([[[7 ,8],[9 ,10],[11 ,12]]])

print(arr3.ndim)
print("concatenate: ",np.concatenate([arr3, arr4]))

print(np.ravel([arr3,arr4]))

concatenate:  [1 2 3 4 5 6 7 8]
3
concatenate:  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


TRANSPOSE - swaps rows and columns
            using .T

In [ ]:
arr3 = np.array([[1 ,2] ,[3 ,4]])
print(arr3.T)
print(arr3.T.T)  # reverse


[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
