MOVIE RATING RECOMMENDATION (Numpy Correlation Project)

~ Find movies with similar ratings using correlation

In [12]:
import numpy as np

np.random.seed(0)
ratings = np.random.randint(1,6,(5,4))


print("Movie ratings: ")
print(ratings)

movie_corr = np.corrcoef(ratings.T)

print("Movie correlation matrix:\n",movie_corr,)
print()
similarities = movie_corr[0]
for i,score in enumerate(similarities):
    print(f"Movie{i + 1}:{score:.2f}")


Movie ratings: 
[[5 1 4 4]
 [4 2 4 3]
 [5 1 1 5]
 [3 2 1 2]
 [2 1 2 5]]
Movie correlation matrix:
 [[ 1.         -0.21004201  0.30343304  0.11764706]
 [-0.21004201  1.          0.06019293 -0.91018205]
 [ 0.30343304  0.06019293  1.         -0.07585826]
 [ 0.11764706 -0.91018205 -0.07585826  1.        ]]

Movie1:1.00
Movie2:-0.21
Movie3:0.30
Movie4:0.12
