Numpy Matrix Operations for Image Processing Stimulation

~ stimulate an image (matrix) and apply brightness and contrast operations

In [1]:
import numpy as np

# creates a 5 x 5 matrix grayscale image (pixel values 0-255)

image = np.random.randint(0,256,(5,5))
print("Original image:\n",image)

# increase brightness
bright_image = image + 50
bright_image = np.clip(bright_image,0,255)

print("\nBright image:\n",bright_image)

# increase contrast
contrast_image = 1.5 * image
contrast_image = np.clip(contrast_image,0,255)

print("\nContrast image:\n",contrast_image.astype(int))

Original image:
 [[246 232 221 184 243]
 [166  17 178  15   9]
 [186  72 193 125  95]
 [220  31   2  83 165]
 [112 188 188  66  73]]

Bright image:
 [[255 255 255 234 255]
 [216  67 228  65  59]
 [236 122 243 175 145]
 [255  81  52 133 215]
 [162 238 238 116 123]]

Contrast image:
 [[255 255 255 255 255]
 [249  25 255  22  13]
 [255 108 255 187 142]
 [255  46   3 124 247]
 [168 255 255  99 109]]
