Numpy Matrix Operations for Image Processing Stimulation

~ stimulate an image (matrix) and apply brightness and contrast operations

In [2]:
import numpy as np

# creates a 5 x 5 matrix grayscale image (pixel values 0-255)

image = np.random.randint(0,256,(5,5))
print("Original image:\n",image)

# increase brightness
bright_image = image + 50
bright_image = np.clip(bright_image,0,255)

print("\nBright image:\n",bright_image)

# increase contrast
contrast_image = 1.5 * image
contrast_image = np.clip(contrast_image,0,255)

print("\nContrast image:\n",contrast_image.astype(int))

Original image:
 [[101  78 121 123 123]
 [ 87  60  53  33 228]
 [119  64 191  58 162]
 [ 18  31 210 197 249]
 [230  24 150 242 121]]

Bright image:
 [[151 128 171 173 173]
 [137 110 103  83 255]
 [169 114 241 108 212]
 [ 68  81 255 247 255]
 [255  74 200 255 171]]

Contrast image:
 [[151 117 181 184 184]
 [130  90  79  49 255]
 [178  96 255  87 243]
 [ 27  46 255 255 255]
 [255  36 225 255 181]]
