STUDENT MARK ANALYSIS

1. Average by subject and student
2. Highest & lowest marks per subject
3. Overall class topper
4. Pass count per subject
5. Which subject is difficult?
6. Ranking Students


students = rows
subjects = columns

In [3]:
import numpy as np

np.random.seed(25)
marks = np.random.randint(1,101 , size=(20,5))
print(marks)
print()

# 1. Average by subject and student

average_by_subjects = np.mean(marks , axis = 0)
print("average by subjects: ",average_by_subjects)
print()

average_by_students = np.mean(marks , axis = 1)
print("average by students: ",average_by_students)
print()

# 2. Highest & lowest per subject

Highest_value = np.max(marks,axis = 0)
lowest_value = np.min(marks,axis = 0)

print("highest marks of subjects: ",Highest_value)
print("lowest marks of subject: ",lowest_value)
print()

# 3. Overall class topper

total_marks = np.sum(marks, axis= 1)
topper = np.argmax(total_marks)

print("total marks :" ,total_marks)
print("topper of the class:",topper,"with marks of",total_marks[topper])
print()

# 4. Pass count per subject

pass_fail = marks >=35
pass_count = np.sum(pass_fail,axis = 0)

print("Pass count by subjects: ",pass_count)

# 5. Which subject is difficult?

diffcult_subject = np.argmin(average_by_subjects)
print("diffcult subject is",diffcult_subject,"with average marks of",average_by_subjects[diffcult_subject])  # index value

# 6. Ranking Students

ranks = np.argsort(-total_marks)
print("First Rank of class",ranks[0])
print("First Rank of class",ranks[:3])



[[ 5 63 91 16 62]
 [24 45 51  9 29]
 [ 5 90 32 70  2]
 [40  4 89 56  4]
 [85 46  4  2 23]
 [32 49 48 74 17]
 [51 86 37 10 33]
 [11 61 48  2 87]
 [92 50 19 93 37]
 [99 31 39  3  6]
 [58 74 23 12  3]
 [44 91 62 85 84]
 [75 18 15 84 38]
 [88 51 52 15 72]
 [63 91 16 15 77]
 [40 89 47 54 30]
 [14 47 54 63 68]
 [ 3 45 45 64 46]
 [25 10 68 60 80]
 [33 96  6 57 37]]

average by subjects:  [44.35 56.85 42.3  42.2  41.75]

average by students:  [47.4 31.6 39.8 38.6 32.  44.  43.4 41.8 58.2 35.6 34.  73.2 46.  55.6
 52.4 52.  49.2 40.6 48.6 45.8]

highest marks of subjects:  [99 96 91 93 87]
lowest marks of subject:  [3 4 4 2 2]

total marks : [237 158 199 193 160 220 217 209 291 178 170 366 230 278 262 260 246 203
 243 229]
topper of the class: 11 with marks of 366

Pass count by subjects:  [11 16 13 11 11]
diffcult subject is 4 with average marks of 41.75
First Rank of class 11
First Rank of class [11  8 13]
