STUDENT MARK ANALYSIS

1. Average by subject and student
2. Highest & lowest marks per subject
3. Overall class topper
4. Pass& fail count per subject
5. Which subject is difficult?
6. Ranking Students


students = rows
subjects = columns

In [1]:
import numpy as np

In [11]:
np.random.seed(20)
marks = np.random.randint(1,101 , size=(20,5))
print(marks)

[[100  91  16  96  29]
 [ 91  10  21  76  23]
 [ 72  35  97  41  86]
 [ 91  27  84  17  63]
 [ 17   8  99   7  27]
 [ 14  76  59  26   4]
 [ 75  76  62  78  84]
 [ 58  95  33  11   7]
 [ 76  19   4  78  18]
 [ 44  17  19  80  91]
 [ 60  72  76  30  46]
 [  7  64  79  25  19]
 [ 94  34  79  43  95]
 [  4  19  71  53  23]
 [ 15   5  28  76   9]
 [  7  27  80  83  79]
 [ 11  34  86  18  41]
 [ 83  43  61  85  31]
 [ 37   9  49  20  49]
 [ 96  54  11  39  10]]


In [13]:
# 1. Average by subject and student

average_by_subjects = np.mean(marks , axis = 0)
print("average by subjects: ",average_by_subjects)

average_by_students = np.mean(marks , axis = 1)
print("average by students: ",average_by_students)

average by subjects:  [52.6  40.75 55.7  49.1  41.7 ]
average by students:  [66.4 44.2 66.2 56.4 31.6 35.8 75.  40.8 39.  50.2 56.8 38.8 69.  34.
 26.6 55.2 38.  60.6 32.8 42. ]


In [18]:
# 2. Highest & lowest per subject

Highest_value = np.max(marks,axis = 0)
Highest_value_by_student = np.argmax(Highest_value)
lowest_value = np.min(marks,axis = 0)
lowest_value_by_student = np.argmin(lowest_value)

print("highest marks of subjects: ",Highest_value)
print("lowest marks of subject: ",lowest_value)

highest marks of subjects:  [100  95  99  96  95]
lowest marks of subject:  [4 5 4 7 4]


In [21]:
# 3. Overall class topper

total_marks = np.sum(marks, axis= 1)
topper = np.argmax(total_marks)

print("total marks :" ,total_marks)
print("topper of the class:",topper,"with marks of",total_marks[topper])

total marks : [332 221 331 282 158 179 375 204 195 251 284 194 345 170 133 276 190 303
 164 210]
topper of the class: 6 with marks of [332 221 331 282 158 179 375 204 195 251 284 194 345 170 133 276 190 303
 164 210]


In [23]:
# 4. Pass count per subject

pass_by_subject = marks >= 35
pass_count = np.sum(pass_by_subject,axis = 0)

fail_by_subject = marks < 35
fail_count = np.sum(fail_by_subject,axis = 0)

print("Pass count by subjects: ",pass_count)
print("Fail count by subjects: ",fail_count)

Pass count by subjects:  [13  9 13 12  9]
Fail count by subjects:  [ 7 11  7  8 11]


In [24]:
# 5. Which subject is difficult?

diffcult_subject = np.argmin(average_by_subjects)
print("diffcult subject is",diffcult_subject,"with average marks of",average_by_subjects[diffcult_subject])  # index value

diffcult subject is 1 with average marks of 40.75


In [26]:
# 6. Ranking Students

ranks = np.argsort(-total_marks)     # ( - ) sign is used to sort in descending order
print("First Rank of class",ranks[0])
print("top 3 Ranks of class",ranks[:3])

First Rank of class 6
top 3 Ranks of class [ 6 12  0]
